// <auto-generated />
using System;
using CPLAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CPLAPI.Migrations
{
    [DbContext(typeof(CyberPulseContext))]
    [Migration("20250707105159_NullableEquipo")]
    partial class NullableEquipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("CPLAPI.Models.Agente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rango")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Agentes");
                });

            modelBuilder.Entity("CPLAPI.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especialidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("OperacionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OperacionId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("CPLAPI.Models.Operacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operaciones");
                });

            modelBuilder.Entity("CPLAPI.Models.Agente", b =>
                {
                    b.HasOne("CPLAPI.Models.Equipo", "Equipo")
                        .WithMany("Agentes")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("CPLAPI.Models.Equipo", b =>
                {
                    b.HasOne("CPLAPI.Models.Operacion", "Operacion")
                        .WithMany("Equipos")
                        .HasForeignKey("OperacionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Operacion");
                });

            modelBuilder.Entity("CPLAPI.Models.Equipo", b =>
                {
                    b.Navigation("Agentes");
                });

            modelBuilder.Entity("CPLAPI.Models.Operacion", b =>
                {
                    b.Navigation("Equipos");
                });
#pragma warning restore 612, 618
        }
    }
}
